### ISSUE TITLE
applicationName not recognized by gradle

### ISSUE THREAD

**Issue by axsddlr** [sababado/AndroidApkRename#1]
error occurs upon gradle syncing with 'applicationName'

**Comment by sababado** [comment]
Can you provide more details please? I'm not able to reproduce.

What version of the plugin are you using, and if possible can you provide a buildscript snippet?

**Comment by axsddlr** [comment]
I've since then reverted however, ill re t ry and give you info in a few hrs

**Comment by sababado** [comment]
Thank you. Yeah give me all the details you can please
